"""Listas compartidas de variables para EDA y modelado."""

VARIABLES_NUMERICAS = [
    'EDAD',
    'ANTIGUEDAD_MESES',
    'INGRESOS_MENSUALES',
    'EGRESOS_MENSUALES',
    'MONTO_TRANSACCION',
    'DISTANCIA_UBICACION_KM',
    'NUM_TRANSACCIONES_DIA',
    'MONTO_PROMEDIO_30D',
    'NUM_INTENTOS_FALLIDOS',
]

VARIABLES_CATEGORICAS_EDA = [
    'SEXO',
    'SEGMENTO',
    'CANAL',
    'PAIS_DESTINO',
    'CIUDAD',
    'TIPO_CLIENTE',
    'TIPO_TRANSACCION',
    'DISPOSITIVO_NUEVO',
    'CAMBIO_CLAVE_RECIENTE',
    'BENEFICIARIO_NUEVO',
]

VARIABLES_CATEGORICAS_CRAMER = [
    'SEXO',
    'TIPO_CLIENTE',
    'SEGMENTO',
    'TIPO_TRANSACCION',
    'CANAL',
    'CIUDAD',
    'PAIS_DESTINO',
    'DISPOSITIVO_NUEVO',
    'CAMBIO_CLAVE_RECIENTE',
    'CLIENTE_NUEVO',
    'BENEFICIARIO_NUEVO',
    'FIN_DE_SEMANA',
]

VARIABLES_CATEGORICAS_MODELO = [
    'SEXO',
    'SEGMENTO',
    'CANAL',
    'PAIS_DESTINO',
    'CIUDAD',
    'TIPO_CLIENTE',
    'TIPO_TRANSACCION',
    'DISPOSITIVO_NUEVO',
    'CAMBIO_CLAVE_RECIENTE',
    'BENEFICIARIO_NUEVO',
    'CLIENTE_NUEVO',
    'OPERACION_NOCTURNA',
    'FIN_DE_SEMANA',
]

VARIABLES_TOTALES_MODELO = VARIABLES_NUMERICAS + VARIABLES_CATEGORICAS_MODELO
